version: '3.8'

services:
  mcp_service:
    build: .
    container_name: mcp_data_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - APP_PORT=8000
      - DEBUG=False
      - LOG_LEVEL=INFO
      - API_KEY_REQUIRED=False
    depends_on:
      - postgres
    networks:
      - mcp_network

  postgres:
    image: postgres:15
    container_name: mcp_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge

volumes:
  postgres_data: