[project]
name = "commondataanalysis"
version = "0.1.0"
description = "MCP server for CSV data analysis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.1",
    "pandas>=2.0.0",
]
